### Get all technicians
GET http://localhost:8081/technicians

### Search technicians by expertise 
GET http://localhost:8081/search/Electrician

### Search technicians by name 
GET http://localhost:8081/search?name=Max

### Search technicians by ID 
GET http://localhost:8081/search?id=1

### Search technicians by ID 
GET http://localhost:8081/search?id=2



###ดูสถานที่ของลูกค้า
GET http://localhost:8080/technician-access/location?customerName=Simon
Content-Type: application/json


### DELETE การจองนัด 
DELETE http://localhost:8081/delete/cancel-booking-tech?technicianId=2&customerName=Betty
Content-Type: application/json
